SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;

CREATE TABLE `userlog` (
  `ID` int(11) NOT NULL,
  `VPN` text NOT NULL,
  `IP` text NOT NULL,
  `PROVIDER` text NOT NULL,
  `COUNTRY` text NOT NULL,
  `REGION` text NOT NULL,
  `CITY` text NOT NULL,
  `TIME` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `userlog`
  ADD PRIMARY KEY (`ID`);

ALTER TABLE `userlog`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;
